### ISSUE TITLE
No longer working in kiwi browser 

### ISSUE THREAD

**Issue by superslayer0040** [hive-keychain/hive-keychain-extension#240]
![Screenshot_2022-06-22-11-35-28-216_com kiwibrowser browser](https://user-images.githubusercontent.com/67392794/174938203-535737b0-d0da-4540-bd04-65bd6dc98a56.jpg)

**Comment by cedricguillas** [comment]
Hi @superslayer0040 ! Unfortunately we don't support Kiwi browser.
If you want to use it on computer, you can download Brave, Google Chrome or Firefox. You can also use the mobile application we have available on Android and IOS.

**Comment by superslayer0040** [comment]
Thought you say so,
.yeah,for now im using hiveauth..kiwi always update it version to match latest chromium,..i guess untill then,no offense but i like using extension more which also developed by you 😂,it just felt more interactive to me..

**Comment by stoodkev** [comment]
The thing is the way it works, it's not easy for us to debug on Kiwi in development.
If their Chromium is up to date it should work though. The error you are showing in the screenshot is not really an error, it just means that Keychain received the request and is waiting for the popup to open.

**Comment by superslayer0040** [comment]
Somehow I managed to get the extension worked  again without needed to wait for the browser to be updated.anyway,thanks for even replied.You guys did a good work so far.
