### ISSUE TITLE
Keychain 2.4.2 is not returning broadcasted transaction ID

### ISSUE THREAD

**Issue by reazuliqbal** [hive-keychain/hive-keychain-extension#408]
Older Keychain used to return transaction ID as part of the `result` object, this new version is returning `return: true`. Many Hive-Engine services depend on Keychain returning the broadcasted transaction ID as part of the success message.

Is it possible to start returning the transaction ID again?

**Comment by cedricguillas** [comment]
We fixed this issue already. V2.4.6 is already online

**Comment by reazuliqbal** [comment]
Firefox addon weren't updated then, probably was in review. Got the update today. All good now. Thanks.
