### ISSUE TITLE
Cannot Make Transfer Through Keychain Version 2.4.8

### ISSUE THREAD

**Issue by BartolomeoItaliano** [hive-keychain/hive-keychain-extension#417]
When I click on username input whole application crashes. With following message:

![asdf](https://user-images.githubusercontent.com/26720699/230641022-47401cba-65e7-4b44-a19a-f75caca870a2.PNG)

**Comment by stoodkev** [comment]
Hi,

In the console, type this :

 `await chrome.storage.local.set({'LOCAL_STORAGE_VERSION':3})`

Then on your browser's extensions management page, toggle keychain off then
on again. It should fix the issue.

**Comment by BartolomeoItaliano** [comment]
Worked, thanks!
