### ISSUE TITLE
Error thrown after loading keychain extension 

### ISSUE THREAD

**Issue by shawnpringle** [hive-keychain/hive-keychain-extension#461]
The error gets thrown here.  The obj is null or undefined.

const startClaimRewards = obj => {
  if (rewardInterval) clearTimeout(rewardInterval);
  const users = Object.keys(obj);
  iterateClaimRewards(users);
  rewardInterval = setInterval(async () => {
    iterateClaimRewards(users);
  }, 1200 * 1000);
};

Stack trace:
js/background/autoClaims.js:6 (startClaimRewards)
js/background/init.js:19 (anonymous function)

The error happens in v1.10.6 and HEAD.

**Comment by cedricguillas** [comment]
Version 1.10 ? If it’s the case, you are using a very old version. I would
suggest you update your extension

**Comment by stoodkev** [comment]
If you have the same issue in HEAD we'll need the stacktrace from that version. v1.10 is almost three years old
