### ISSUE TITLE
Remove display of private keys for Authorized Accounts

### ISSUE THREAD

**Issue by VIM-Arcange** [hive-keychain/hive-keychain-extension#47]
![image](https://user-images.githubusercontent.com/21260036/80629334-fd4f3780-8a52-11ea-99f8-c232c806c6d6.png)

When adding an Authorized Account, the management page allows you to display the delegatee's private keys, which might be confusing for users. The "click to show private key" links should be hidden.

**Comment by stoodkev** [comment]
Maybe it should be `Click to show @arcange's private key` instead ?

**Comment by 4Ykw** [comment]
Is the private key really accessible via @arcange-ru? no right... then it can only be because the extension recognizes it and shows it from its source.

So my suggestion would be to make the link go to the account that has that key, and there you can click to reveal if you need to.

Does that help your worries @VIM-Arcange ?

**Comment by VIM-Arcange** [comment]
> Is the private key really accessible via @arcange-ru?

Yes, it is.  If I click on the link, keychain will display the private key of @arcange because it has been added to keychain too.  
But I do not see any reason to display it while I'm managing @arcange-ru account.  

My suggestion is to **remove** the link. I don't need to jump to another account.

**Comment by 4Ykw** [comment]
> because it has been added to keychain too.

This is what meant with:

> because the extension recognizes it and shows it from its source.

The extension already has the key (the @arcange one) in the extension... and therefore will know it.

I will try this, but can you try to remove @arcange from the extension, and check it will stop showing that?

**Comment by stoodkev** [comment]
I still think it makes sense to show the key that would be used to perform a certain type of transactions here.
You ll use @arcange posting key if you perform posting transactions with @arcange-ru. 
And if you Remove the key, you re not removing the original key, you re just telling Keychain to forget that @arcange-ru should use @arcange posting key for signing posting auth broadcasts.

**Comment by VIM-Arcange** [comment]
It's not @arcange-ru performing operations, it's @arcange using his own posting key and broadcasting operations that contain @arcange-ru as the "operator". And as posting auth has been delegated by @arcange-ru to @arcange, it will be accepted by the blockchain.

Regarding key removal, you can discard my previous comment. I messed up with who delegated auth to who.
