### ISSUE TITLE
[Bug] Hive Engine total token value adding total unstaking tokens in full+staked

### ISSUE THREAD

**Issue by forkyishere** [hive-keychain/hive-keychain-extension#487]
Just found that here:

https://github.com/hive-keychain/hive-keychain-extension/blob/ffdec1303716f6b8883b97ff6413b90590e905c7/src/popup/hive/utils/tokens.utils.ts#L311

The amount is negligible if very small so I never noticed, but when I unstaked all of the balance, I noticed this. Where it adds 75% more value in this case (for a 4-period unstaking token).

I think the best to do here, is to NOT sum the total pending unstaking, and instead calculate the total using the "period amount unstaking" (that is not visible on the staked amount anymore).

When periods advance, the total staked tokens will further reduce and add up with the already in liquid.

Pics (tested with version 3.1.4):
![image](https://github.com/hive-keychain/hive-keychain-extension/assets/114926085/e92d0619-8cc4-4e41-a10a-75c09f8a20a3)

![image](https://github.com/hive-keychain/hive-keychain-extension/assets/114926085/52fb6013-eeb2-4e1a-9fbd-4133ee04d442)

CC @cedricguillas

**Comment by stoodkev** [comment]
Thanks for referencing the issue, it has been fixed and will be pushed in the live prod version
