### ISSUE TITLE
Add Hive Slot Games to Ecosystem tab

### ISSUE THREAD

**Issue by BartolomeoItaliano** [hive-keychain/hive-keychain-extension#506]
I want to ask, to have my webpage "Hive Slot Games" added to the ecosystem tab in the app.

https://hiveslotgames.com/

What data I need to provide to achieve that?

I hope, I am making the request in proper place.

**Comment by stoodkev** [comment]
Hi, please give us the following

Name
Description (keep it short, see others in ecosystem)
URL 
Mobile URL if different
Icon URL

**Comment by BartolomeoItaliano** [comment]
Here they are:

Name: Hive Slot Games
Description: Your Luck, Your Fortune, Your Casino!
URL: https://hiveslotgames.com/
Icon URL: https://hiveslotgames.com/assets/icons/ssg.png


I would also have another question:
What can I do to show up on the top of list in the ecosystem tab?
I would like to advertise better with your great app.

**Comment by BartolomeoItaliano** [comment]
Hello @stoodkev when can I expect to be added to the app?
