### ISSUE TITLE
Additional redirection suggestion from browser to Keychain app

### ISSUE THREAD

**Issue by BartolomeoItaliano** [hive-keychain/hive-keychain-extension#509]
Currently on mobile phones, if you redirect from web browser it only takes you to keychain mobile app.

Example:
1. User clicks go to keychain app on webpage.
2. He is being taken to main view of Keychain mobile app.
![Uploading Screenshot_20240604_152717_Settings.jpg…]()

Expected behavior:
1. User is being taken to Keychain app into the ecosystem tab and "url" is filled with the one he came from the original browser.
2. Internal Keychain browser automatically opens the webpage.

I believe it might help users engaging with their favorite app and help with onboarding new people to Hive ecosystem.

**Comment by stoodkev** [comment]
Duely noted but this is the extension repository.
Closing the issue here.
