### ISSUE TITLE
Display pending HBD to HIVE conversion(s)

### ISSUE THREAD

**Issue by VIM-Arcange** [hive-keychain/hive-keychain-extension#95]
When you convert HBD to HIVE conversion, the amount of HBD converted is moved into "limbo" for 3.5 days and is deduced from your liquid HBD

It would be nice if Keychain could display information about pending conversions (like peakd does):
![image](https://user-images.githubusercontent.com/21260036/122165121-0c23c400-ce78-11eb-8fe6-66ffd3df2879.png)

**Comment by stoodkev** [comment]
I dont want to put too much info on the main screen and make it difficultly readable .
However, we can add a list of current conversions to the conversion screen, the same way we are showing current delegations on the delegation page.

**Comment by VIM-Arcange** [comment]
A small icon with a tooltip like "n HBD pending conversion" would be enough for me.
More details on a separate page would be the icing on the cake
